<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <Version>1.1.0-preview.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="app.ico" />
    <EmbeddedResource Include="Guida.it.html" WithCulture="false" LogicalName="RemoteLogViewer.Guida.it.html" />
    <EmbeddedResource Include="Guida.en.html" WithCulture="false" LogicalName="RemoteLogViewer.Guida.en.html" />
  </ItemGroup>

</Project>
